spring.application.name=Sunday-CC-Week47-MiniLoadBalancer

# Database 1 Configuration
app.datasource.db1.jdbc-url=jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1;INIT=CREATE TABLE IF NOT EXISTS entries (id BIGINT AUTO_INCREMENT PRIMARY KEY)
app.datasource.db1.username=sa
app.datasource.db1.password=
app.datasource.db1.driver-class-name=org.h2.Driver

# Database 2 Configuration
app.datasource.db2.jdbc-url=jdbc:h2:mem:db2;DB_CLOSE_DELAY=-1;INIT=CREATE TABLE IF NOT EXISTS entries (id BIGINT AUTO_INCREMENT PRIMARY KEY)
app.datasource.db2.username=sa
app.datasource.db2.password=
app.datasource.db2.driver-class-name=org.h2.Driver

# Database 3 Configuration
app.datasource.db3.jdbc-url=jdbc:h2:mem:db3;DB_CLOSE_DELAY=-1;INIT=CREATE TABLE IF NOT EXISTS entries (id BIGINT AUTO_INCREMENT PRIMARY KEY)
app.datasource.db3.username=sa
app.datasource.db3.password=
app.datasource.db3.driver-class-name=org.h2.Driver

# Standard Spring JPA configurations
spring.jpa.show-sql=true
